test:
  php53:
    branch:
      box: 'octo-leam-php53'
      dir: '{home}/github'
      env_vars:
        docroot: '{home}/www'
        domain: 'localhost'
        database_name: 'test'
        database_user: 'test'
        database_pass: ''
        account_user: admin
        account_mail: admin@zen.ci
        account_pass: REPLACE_WITH_ADMIN_PASSWORD
        site_mail: noreply@zen.ci
        site_name: 'branch {branch} tests for {repo_owner}/{repo_name}'
        tests: '--directory sites/all/modules/custom/views'
      scripts:
        init: '{deploy_dir}/scripts/deploy_init.sh'
      tests:
        - '{deploy_dir}/scripts/drupal_tests.php'
    pull_request:
      box: 'octo-leam-php53'
      dir: '{home}/github'
      env_vars:
        docroot: '{home}/www'
        domain: 'localhost'
        database_name: 'test'
        database_user: 'test'
        database_pass: ''
        account_user: admin
        account_mail: admin@zen.ci
        account_pass: REPLACE_WITH_ADMIN_PASSWORD
        site_mail: noreply@zen.ci
        site_name: 'PR {pr_number} branch {branch} tests for {repo_owner}/{repo_name}'
        tests: 'Views'        
      scripts:
        init: '{deploy_dir}/scripts/deploy_init.sh'
      tests:
        - '{deploy_dir}/scripts/drupal_tests.php'
